application: agile-server-app
version: 1
runtime: python
api_version: 1

handlers:
- url: /subscribe
  script: subscription.py

- url: /github
  script: github.py
  
- url: /tasks/github
  script: github_task.py
  login: admin
  
- url: /
  script: not_accepted.py

- url: /.*
  script: not_accepted.py

