application: agimanserver
version: 1
runtime: python
api_version: 1

handlers:
- url: /subscribe
  script: publishsubscribeserver/subscription.py
#  login: required

- url: /github
  script: publishsubscribeserver/github.py
  
- url: /tasks/github
  script: publishsubscribeserver/github_task.py
  login: admin
  
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  mime_type: image/vnd.microsoft.icon
  upload: static/images/favicon.ico
  
- url: /
  script: publishsubscribeserver/not_accepted.py

- url: /.*
  script: publishsubscribeserver/not_accepted.py
  
derived_file_type:
- python_precompiled

